            - name: Databricks Asset Bundles Deploy
  # You may pin to the exact commit or the version.
  # uses: LumiaStudios/Databricks-Asset-Bundles-Deploy@258bf6125568a7dbd97bb9a7257f0927e0db0db5
  uses: LumiaStudios/Databricks-Asset-Bundles-Deploy@v1.0.0
  with:
    # The directory containing the Databricks asset bundle configuration
    working-directory: 
    # The Databricks workspace host URL
    databricks-host: 
    # The target environment for the Databricks asset bundle deployment
    databricks-bundle-env: 
    # The type of authentication to use (token or oauth)
    authentication-type: # default is token
    # Databricks personal access token for authentication
    databricks-token: # optional
    # Databricks OAuth client ID for authentication
    databricks-client-id: # optional
    # Databricks OAuth client secret for authentication
    databricks-client-secret: # optional
    # Azure Managed Identity or Microsoft Entra ID client ID
    arm-client-id: # optional
    # Microsoft Entra ID client secret
    arm-client-secret: # optional
    # Microsoft Entra ID tenant ID
    arm-tenant-id: # optional
    # Google Cloud credentials for authentication
    google-credentials: # optional
          
